### ISSUE TITLE
Parsing a potentially bad heading

### ISSUE THREAD

**Issue by MisterBianco** [NimParsers/parsetoml#36]
I am trying to parse my aws config file and it has entries like:

```toml
[profile master]
region = us-west-2
output = text
adfs_config.ssl_verification = False
adfs_config.role_arn = <REDACTED>
adfs_config.adfs_host =<REDACTED>
adfs_config.adfs_user =<REDACTED>
adfs_config.session_duration = 3600
adfs_config.provider_id = urn:amazon:webservices
```

However, when I use parseFile to... parse... the... file 😆, I get the following error:

```
/Users/user/development/awslogin/awslogin.nim(6) awslogin
/Usersuser/.nimble/pkgs/parsetoml-0.5.0/parsetoml.nim(1285) parseFile
/Users/user/.nimble/pkgs/parsetoml-0.5.0/parsetoml.nim(1242) parseStream
/Usersuser/.nimble/pkgs/parsetoml-0.5.0/parsetoml.nim(966) parseTableName
Error: unhandled exception: /Users/user/.aws/config(1:11) unexpected character "m" [TomlError]
``` 

I know this is due to the heading but I dont know if it is part of the official spec.
